- hosts: localhost

  tasks:
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: TRTesting
      name: narwhal249448fsad
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: TRTesting
      name: testvn001
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: TRTesting
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: TRTesting
      allocation_method: Static
      name: publicip001

  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: TRTesting
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: TRTesting
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: TRTesting
      name: cheftest
      vm_size: Standard_D1
      storage_account: narwhal249448fsad
      storage_container: narwhalcont234
      storage_blob: testvm001.vhd
      admin_username: marajade
      admin_password: P@ssw0rd.1!!
      network_interfaces: testnic001
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
